image: python:3.8-alpine3.18

clone:
  depth: full

definitions:
  steps:
    - step: &execute-scan-with-veracode
        name: Execute Scan With Veracode
        script:
          - apk add zip curl
          - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          - zip -r app.zip ./
          - ./veracode static scan app.zip --results-file scan-results.json
        artifacts:
          - scan-results.json

    - step: &execute-scan-with-wiz
        name: Execute Scan With Wiz
        deployment: aws-prod
        script: 
          - apk add curl jq
          - pip install awscli
          - curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
          - export WIZ_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id $ENV/credentials/wiz --output text --query "SecretString")
          - ./wizcli auth --id "$(echo $WIZ_CREDENTIALS | jq -r .client_id)" --secret "$(echo $WIZ_CREDENTIALS | jq -r .client_secret)"
          - ./wizcli iac scan --path . --name "$BITBUCKET_REPO_SLUG" --tag repository="$BITBUCKET_REPO_SLUG" --tag branch="$BITBUCKET_BRANCH" --format human --output wiz_iac_scan_results.json
          - ./wizcli dir scan --path . --name "$BITBUCKET_REPO_SLUG" --tag repository="$BITBUCKET_REPO_SLUG" --tag branch="$BITBUCKET_BRANCH" --format human --output wiz_dir_scan_results.json
        artifacts:
          - "*_scan_results.json"

pipelines:
  branches:
    "{feature/*,bugfix/*,hotfix/*}":
    - parallel:
      - step: *execute-scan-with-veracode
      - step: *execute-scan-with-wiz

    main:
      - step: *execute-scan-with-veracode
      - step: *execute-scan-with-wiz